/* ../local/config.h.  Generated by configure.  */
#ifndef __UX_CONFIG_H__
#define __UX_CONFIG_H__

/* #undef __EXTENSIONS__ */

/* Define to 1 if you have the <sys/types.h> header file. */
#define UX_HAVE_SYS_TYPES_H 1
/* Define to 1 if you have the <stdint.h> header file. */
#define UX_HAVE_STDINT_H 1
/* Define to 1 if you have the <inttypes.h> header file. */
#define UX_HAVE_INTTYPES_H 1
/* Define to 1 if you have the <stdlib.h> header file. */
#define UX_HAVE_STDLIB_H 1
/* Define to 1 if you have the <string.h> header file. */
#define UX_HAVE_STRING_H 1
/* Define to 1 if you have the <time.h> header file. */
#define UX_HAVE_TIME_H 1
/* Define to 1 if you have the <sys/time.h> header file. */
#define UX_HAVE_SYS_TIME_H 1
/* Define to 1 if you have the <sys/select.h> header file. */
#define UX_HAVE_SYS_SELECT_H 1
/* Define to 1 if you have the <sys/socket.h> header file. */
#define UX_HAVE_SYS_SOCKET_H 1
/* Define to 1 if you have the <sys/filio.h> header file. */
/* #undef UX_HAVE_SYS_FILIO_H */
/* Define to 1 if you have the <sys/epoll.h> header file. */
#define UX_HAVE_SYS_EPOLL_H 1
/* Define to 1 if you have the <sys/devpoll.h> header file. */
/* #undef UX_HAVE_SYS_DEVPOLL_H */
/* Define to 1 if you have the <sys/event.h> header file. */
/* #undef UX_HAVE_SYS_EVENT_H */
/* Define to 1 if you have the <openssl/ssl.h> header file. */
/* #undef UX_HAVE_OPENSSL_SSL_H */


/* Define to 1 if you have the type 'struct timeval'. */
#define UX_HAVE_STRUCT_TIMEVAL 1
/* Define to 1 if you have the type 'struct tm'. */
/* #undef UX_HAVE_STRUCT_TM */


/* Define to 1 if you have the function 'localtime_r'. */
#define UX_HAVE_LOCALTIME_R 1
/* Define to 1 if you have the function 'strlcpy'. */
/* #undef UX_HAVE_STRLCPY */
/* Define to 1 if you have the function 'strlcat'. */
/* #undef UX_HAVE_STRLCAT */
/* Define to 1 if you have the function 'inet_ntop'. */
#define UX_HAVE_INET_NTOP 1
/* Define to 1 if you have the function 'inet_pton'. */
#define UX_HAVE_INET_PTON 1
/* Define to 1 if you have the function 'semtimedop'. */
#define UX_HAVE_SEMTIMEDOP 1

/* Define to 1 if compiler provides atomic builtins. */
#define UX_HAVE_ATOMIC_BUILTINS 1

/* Define to 1 if your system is BIGENDIAN. */
/* #undef UX_BIGENDIAN */

/* #undef const */

#define UX_INLINE inline

#define UX_HAVE_INLINE 1

#define UX_HAVE_IN6 1

/* #undef UX_HAVE_SOCKADDR_SA_LEN */

#define UX_HAVE_ADDRINFO 1

#define UX_HAVE_MSG_TRUNC 1


#endif // #ifndef __UX_CONFIG_H__
