#include "gw/gw_error.h"

UX_DECLARE(uint32_t) gw_err_to_rcode( int err)
{
	switch( err) {
		case GW_ERR_BAD_REQUEST :
		case GW_ERR_NO_IMPI :
		case GW_ERR_NO_IMPU :
		case GW_ERR_NO_VNETID :
		case GW_ERR_NO_MALFORMED_CONTACT :
			return 400;
		case GW_ERR_INVALID_SCSCF_URI :
		case GW_ERR_RCV_DIA_ERROR :
		case GW_ERR_AUTHORIZATION_REJECTED :
		case GW_ERR_UNABLE_TO_COMPLY :
		case GW_ERR_RCV_3GPP_ERROR :
		case GW_ERR_USER_UNKNOWN :
		case GW_ERR_IDENTITIES_DONT_MATCH :
		case GW_ERR_ROAMING_NOT_ALLOWED :
		case GW_ERR_IDENTITY_NOT_REGISTERED :
		case GW_ERR_IDENTITY_ALREADY_REGISTERED :
		case GW_ERR_AUTH_SCHEME_NOT_SUPPORTED :
		case GW_ERR_IN_ASSIGNMENT_TYPE :
		case GW_ERR_TOO_MUCH_DATA :
		case GW_ERR_NOT_SUPPORTED_USER_DATA :
		case GW_ERR_FEATURE_UNSUPPORTED :
			return 403;
		case GW_ERR_DIA_TIMEOUT :
		case GW_ERR_DIA_MISSING_AVP :
		case GW_ERR_DIA_ERROR :
		case GW_ERR_DIA_SEND_FAIL :
		case GW_ERR_UNREGISTERED_SERVICE :
		case GW_ERR_SERVER_NAME_NOT_STORED :
			return 480;
		case GW_ERR_NO_MEMORY :
		case GW_ERR_SERVICE_LOGIC :
		case GW_ERR_SET_AVP :
			return 500;
		case GW_ERR_TIMEOUT :
			return 504;
		case GW_ERR_NO_SCSCF :
			return 600;
		default: break;
	}
	return 200;
}

UX_DECLARE(const char*) gw_err_to_phrase( int err)
{
	switch( err) {
		case GW_ERR_BAD_REQUEST : return GW_SIPPHRASE_400_BAD_REQUEST;
		case GW_ERR_NO_IMPI : return GW_SIPPHRASE_400_NO_IMPI;
		case GW_ERR_NO_IMPU : return GW_SIPPHRASE_400_NO_IMPU; 
		case GW_ERR_NO_VNETID : return GW_SIPPHRASE_400_NO_VNETID;
		case GW_ERR_NO_MALFORMED_CONTACT : return GW_SIPPHRASE_400_MALFORMED_CONTACT;

		case GW_ERR_INVALID_SCSCF_URI : return GW_SIPPHRASE_403_INVALID_SCSCF_URI;
		case GW_ERR_RCV_DIA_ERROR : return GW_SIPPHRASE_403_RCV_DIA_ERROR;
		case GW_ERR_AUTHORIZATION_REJECTED : return GW_SIPPHRASE_403_AUTHORIZATION_REJECTED;
		case GW_ERR_UNABLE_TO_COMPLY : return GW_SIPPHRASE_403_UNABLE_TO_COMPLY;
		case GW_ERR_RCV_3GPP_ERROR : return GW_SIPPHRASE_403_RCV_3GPP_ERROR;
		case GW_ERR_USER_UNKNOWN : return GW_SIPPHRASE_403_USER_UNKNOWN;
		case GW_ERR_IDENTITIES_DONT_MATCH : return GW_SIPPHRASE_403_IDENTITIES_DONT_MATCH;
		case GW_ERR_ROAMING_NOT_ALLOWED : return GW_SIPPHRASE_403_ROAMING_NOT_ALLOWED;
		case GW_ERR_IDENTITY_NOT_REGISTERED : return GW_SIPPHRASE_403_IDENTITY_NOT_REGISTERED;
		case GW_ERR_IDENTITY_ALREADY_REGISTERED : return GW_SIPPHRASE_403_IDENTITY_ALREADY_REGISTERED;
		case GW_ERR_AUTH_SCHEME_NOT_SUPPORTED : return GW_SIPPHRASE_403_AUTH_SCHEME_NOT_SUPPORTED;
		case GW_ERR_IN_ASSIGNMENT_TYPE : return GW_SIPPHRASE_403_IN_ASSIGNMENT_TYPE;
		case GW_ERR_TOO_MUCH_DATA : return GW_SIPPHRASE_403_TOO_MUCH_DATA;
		case GW_ERR_NOT_SUPPORTED_USER_DATA : return GW_SIPPHRASE_403_NOT_SUPPORTED_USER_DATA;
		case GW_ERR_FEATURE_UNSUPPORTED : return GW_SIPPHRASE_403_FEATURE_UNSUPPORTED;

		case GW_ERR_DIA_TIMEOUT : return GW_SIPPHRASE_480_DIA_TIMEOUT;
		case GW_ERR_DIA_MISSING_AVP : return GW_SIPPHRASE_480_DIA_MISSING_AVP;
		case GW_ERR_DIA_ERROR : return GW_SIPPHRASE_480_DIA_ERROR;
		case GW_ERR_DIA_SEND_FAIL : return GW_SIPPHRASE_480_DIA_SEND_FAIL;
		case GW_ERR_UNREGISTERED_SERVICE : return GW_SIPPHRASE_480_UNREGISTERED_SERVICE; 
		case GW_ERR_SERVER_NAME_NOT_STORED : return GW_SIPPHRASE_480_SERVER_NAME_NOT_STORED; 

		case GW_ERR_NO_MEMORY : return GW_SIPPHRASE_500_NO_MEMORY;
		case GW_ERR_SERVICE_LOGIC : return GW_SIPPHRASE_500_SERVICE_LOGIC;
		case GW_ERR_SET_AVP : return GW_SIPPHRASE_500_SET_AVP;

		case GW_ERR_TIMEOUT : return GW_SIPPHRASE_504_TIMEOUT;

		case GW_ERR_NO_SCSCF : return GW_SIPPHRASE_600_NO_SCSCF;

		default: break;
	}
	return "OK";
}
