#include "clicktocall/clicktocall_error.h"

UX_DECLARE(uint32_t) clicktocall_err_to_rcode( int err)
{
	switch( err) {
		case CLICKTOCALL_ERR_BAD_REQUEST :
		case CLICKTOCALL_ERR_NO_IMPI :
		case CLICKTOCALL_ERR_NO_IMPU :
		case CLICKTOCALL_ERR_NO_VNETID :
		case CLICKTOCALL_ERR_NO_MALFORMED_CONTACT :
			return 400;
		case CLICKTOCALL_ERR_INVALID_SCSCF_URI :
		case CLICKTOCALL_ERR_RCV_DIA_ERROR :
		case CLICKTOCALL_ERR_AUTHORIZATION_REJECTED :
		case CLICKTOCALL_ERR_UNABLE_TO_COMPLY :
		case CLICKTOCALL_ERR_RCV_3GPP_ERROR :
		case CLICKTOCALL_ERR_USER_UNKNOWN :
		case CLICKTOCALL_ERR_IDENTITIES_DONT_MATCH :
		case CLICKTOCALL_ERR_ROAMING_NOT_ALLOWED :
		case CLICKTOCALL_ERR_IDENTITY_NOT_REGISTERED :
		case CLICKTOCALL_ERR_IDENTITY_ALREADY_REGISTERED :
		case CLICKTOCALL_ERR_AUTH_SCHEME_NOT_SUPPORTED :
		case CLICKTOCALL_ERR_IN_ASSIGNMENT_TYPE :
		case CLICKTOCALL_ERR_TOO_MUCH_DATA :
		case CLICKTOCALL_ERR_NOT_SUPPORTED_USER_DATA :
		case CLICKTOCALL_ERR_FEATURE_UNSUPPORTED :
			return 403;
		case CLICKTOCALL_ERR_DIA_TIMEOUT :
		case CLICKTOCALL_ERR_DIA_MISSING_AVP :
		case CLICKTOCALL_ERR_DIA_ERROR :
		case CLICKTOCALL_ERR_DIA_SEND_FAIL :
		case CLICKTOCALL_ERR_UNREGISTERED_SERVICE :
		case CLICKTOCALL_ERR_SERVER_NAME_NOT_STORED :
			return 480;
		case CLICKTOCALL_ERR_NO_MEMORY :
		case CLICKTOCALL_ERR_SERVICE_LOGIC :
		case CLICKTOCALL_ERR_SET_AVP :
			return 500;
		case CLICKTOCALL_ERR_TIMEOUT :
			return 504;
		case CLICKTOCALL_ERR_NO_SCSCF :
			return 600;
		default: break;
	}
	return 200;
}

UX_DECLARE(const char*) clicktocall_err_to_phrase( int err)
{
	switch( err) {
		case CLICKTOCALL_ERR_BAD_REQUEST : return CLICKTOCALL_SIPPHRASE_400_BAD_REQUEST;
		case CLICKTOCALL_ERR_NO_IMPI : return CLICKTOCALL_SIPPHRASE_400_NO_IMPI;
		case CLICKTOCALL_ERR_NO_IMPU : return CLICKTOCALL_SIPPHRASE_400_NO_IMPU; 
		case CLICKTOCALL_ERR_NO_VNETID : return CLICKTOCALL_SIPPHRASE_400_NO_VNETID;
		case CLICKTOCALL_ERR_NO_MALFORMED_CONTACT : return CLICKTOCALL_SIPPHRASE_400_MALFORMED_CONTACT;

		case CLICKTOCALL_ERR_INVALID_SCSCF_URI : return CLICKTOCALL_SIPPHRASE_403_INVALID_SCSCF_URI;
		case CLICKTOCALL_ERR_RCV_DIA_ERROR : return CLICKTOCALL_SIPPHRASE_403_RCV_DIA_ERROR;
		case CLICKTOCALL_ERR_AUTHORIZATION_REJECTED : return CLICKTOCALL_SIPPHRASE_403_AUTHORIZATION_REJECTED;
		case CLICKTOCALL_ERR_UNABLE_TO_COMPLY : return CLICKTOCALL_SIPPHRASE_403_UNABLE_TO_COMPLY;
		case CLICKTOCALL_ERR_RCV_3GPP_ERROR : return CLICKTOCALL_SIPPHRASE_403_RCV_3GPP_ERROR;
		case CLICKTOCALL_ERR_USER_UNKNOWN : return CLICKTOCALL_SIPPHRASE_403_USER_UNKNOWN;
		case CLICKTOCALL_ERR_IDENTITIES_DONT_MATCH : return CLICKTOCALL_SIPPHRASE_403_IDENTITIES_DONT_MATCH;
		case CLICKTOCALL_ERR_ROAMING_NOT_ALLOWED : return CLICKTOCALL_SIPPHRASE_403_ROAMING_NOT_ALLOWED;
		case CLICKTOCALL_ERR_IDENTITY_NOT_REGISTERED : return CLICKTOCALL_SIPPHRASE_403_IDENTITY_NOT_REGISTERED;
		case CLICKTOCALL_ERR_IDENTITY_ALREADY_REGISTERED : return CLICKTOCALL_SIPPHRASE_403_IDENTITY_ALREADY_REGISTERED;
		case CLICKTOCALL_ERR_AUTH_SCHEME_NOT_SUPPORTED : return CLICKTOCALL_SIPPHRASE_403_AUTH_SCHEME_NOT_SUPPORTED;
		case CLICKTOCALL_ERR_IN_ASSIGNMENT_TYPE : return CLICKTOCALL_SIPPHRASE_403_IN_ASSIGNMENT_TYPE;
		case CLICKTOCALL_ERR_TOO_MUCH_DATA : return CLICKTOCALL_SIPPHRASE_403_TOO_MUCH_DATA;
		case CLICKTOCALL_ERR_NOT_SUPPORTED_USER_DATA : return CLICKTOCALL_SIPPHRASE_403_NOT_SUPPORTED_USER_DATA;
		case CLICKTOCALL_ERR_FEATURE_UNSUPPORTED : return CLICKTOCALL_SIPPHRASE_403_FEATURE_UNSUPPORTED;

		case CLICKTOCALL_ERR_DIA_TIMEOUT : return CLICKTOCALL_SIPPHRASE_480_DIA_TIMEOUT;
		case CLICKTOCALL_ERR_DIA_MISSING_AVP : return CLICKTOCALL_SIPPHRASE_480_DIA_MISSING_AVP;
		case CLICKTOCALL_ERR_DIA_ERROR : return CLICKTOCALL_SIPPHRASE_480_DIA_ERROR;
		case CLICKTOCALL_ERR_DIA_SEND_FAIL : return CLICKTOCALL_SIPPHRASE_480_DIA_SEND_FAIL;
		case CLICKTOCALL_ERR_UNREGISTERED_SERVICE : return CLICKTOCALL_SIPPHRASE_480_UNREGISTERED_SERVICE; 
		case CLICKTOCALL_ERR_SERVER_NAME_NOT_STORED : return CLICKTOCALL_SIPPHRASE_480_SERVER_NAME_NOT_STORED; 

		case CLICKTOCALL_ERR_NO_MEMORY : return CLICKTOCALL_SIPPHRASE_500_NO_MEMORY;
		case CLICKTOCALL_ERR_SERVICE_LOGIC : return CLICKTOCALL_SIPPHRASE_500_SERVICE_LOGIC;
		case CLICKTOCALL_ERR_SET_AVP : return CLICKTOCALL_SIPPHRASE_500_SET_AVP;

		case CLICKTOCALL_ERR_TIMEOUT : return CLICKTOCALL_SIPPHRASE_504_TIMEOUT;

		case CLICKTOCALL_ERR_NO_SCSCF : return CLICKTOCALL_SIPPHRASE_600_NO_SCSCF;

		default: break;
	}
	return "OK";
}
