#ifndef __SKB_MSG_INFO_H__
#define __SKB_MSG_INFO_H__

/** @brief define TCP channel info */
#define TCP_CHANNEL_CALL 										0
#define TCP_CHANNEL_RECORDING 									1
#define TCP_CHANNEL_CONFERENCE 									2

/** @brief define DBIF(GW) message ID */
#define DBIF_CALL_START_REQUEST									100
#define DBIF_CALL_STOP_REQUEST									101
#define DBIF_CALL_START_RECORDING_REQUEST						102
#define DBIF_CALL_STOP_RECORDING_REQUEST						103

#define DBIF_CALL_START_RESPONSE								200
#define DBIF_CALL_STOP_RESPONSE									201
#define DBIF_CALL_START_RECORDING_RESPONSE						202
#define DBIF_CALL_STOP_RECORDING_RESPONSE						203
#define DBIF_CALL_SERVICE_STATUS_REPORT							204
#define DBIF_CALL_END_REPORT									205

#define DBIF_CALL_RECORDING_START_REQUEST						300
#define DBIF_CALL_RECORDING_STOP_REQUEST						301

#define DBIF_CALL_RECORDING_START_RESPONSE						400
#define DBIF_CALL_RECORDING_STOP_RESPONSE						401
#define DBIF_RECORDING_CALL_SERVICE_STATUS_REPORT				402
#define DBIF_RECORDING_CALL_END_REPORT							403

#define DBIF_CONFERENCE_START_REQUEST							500
#define DBIF_CONFERENCE_STOP_REQUEST							501
#define DBIF_ADD_PARTY_REQUEST									502
#define DBIF_REMOVE_PARTY_REQUEST								503
#define DBIF_CANCEL_PARTY_REQUEST								504
#define DBIF_CHANGE_PARTY_MEDIA_REQUEST							505
#define DBIF_PLAY_MENT_REQUEST									506
#define DBIF_GET_NUMBER_OF_PARTY_REQUEST						507
#define DBIF_GET_PARTY_STATUS_REQUEST							508

#define DBIF_CONFERENCE_START_RESEPONSE							600
#define DBIF_CONFERENCE_STOP_RESEPONSE							601
#define DBIF_ADD_PARTY_RESEPONSE								602
#define DBIF_REMOVE_PARTY_RESEPONSE								603
#define DBIF_CANCEL_PARTY_RESEPONSE								604
#define DBIF_CHANGE_PARTY_MEDIA_RESEPONSE						605
#define DBIF_PLAY_MENT_RESEPONSE								606
#define DBIF_GET_NUMBER_OF_PARTY_RESEPONSE						607
#define DBIF_GET_PARTY_STATUS_RESEPONSE							608
#define DBIF_ADD_PARTY_REPORT									609
#define DBIF_REMOVE_PARTY_REPORT								610
#define DBIF_CHANGE_PARTY_MEDIA_REPORT							611
#define DBIF_CLOSE_CONF_REPORT									612


/** @brief define TCP(eIPMS) message ID */
#define HEARTBEAT_REQUEST									0x00000000
#define HEARTBEAT_RESEPONSE									0x10000000
#define BINDING_REQUEST										0x00000001
#define BINDING_RESPONSE									0x10000001
#define START_REQUEST										0x00000010
#define START_RESPONSE										0x10000010
#define STOP_REQUEST										0x00000011
#define STOP_RESPONSE										0x10000011
#define STOP_REPORT											0x20000011
#define START_RECORDING_REQUEST								0x00000020
#define START_RECORDING_RESPONSE							0x10000020
#define START_RECORDING_REPORT								0x20000020
#define STOP_RECORDING_REQUEST								0x00000021
#define STOP_RECORDING_RESPONSE								0x10000021
#define STOP_RECORDING_REPORT								0x20000021
#define SERVICE_STATUS_REQUEST								0x00000030
#define SERVICE_STATUS_RESPONSE								0x10000030
#define SERVICE_STATUS_REPORT								0x20000030

/** @brief SKB MAX Message Length */
#define SKB_MSG_MAX_LEN										64*1024
#define SESSION_ID_LEN 										32
#define GW_SESSION_ID_LEN 									32
#define SUBSCRIBER_NAME_LEN									32
#define CALL_NUMBER_LEN										24
#define CHARGING_NUMBER_LEN									24
#define SERVICE_ID_LEN										32
#define CID_LEN												16
#define RECORDING_FILE_URL_LEN								64
#define RECORDING_FILE_NAME_LEN								64
#define SERVICE_TIME_LEN									16

#endif // #ifndef __SKB_MSG_INFO_H__